from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
SRC_DIR = ROOT / "src"
if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

from wine_pgvector_mini.transformer import build_embedding_text_ko


def sql_escape(value: str) -> str:
    return value.replace("'", "''")


def build_update_statement(wine: dict) -> str:
    name_en = wine.get("wine_name") or ""
    name_kr = wine.get("name_kr") or ""
    embedding_text = build_embedding_text_ko(wine)

    where_clauses = []
    if name_en:
        where_clauses.append(f"name_en = '{sql_escape(name_en)}'")
    if name_kr:
        where_clauses.append(f"name_kr = '{sql_escape(name_kr)}'")

    if not where_clauses:
        return ""

    return (
        "UPDATE wine "
        f"SET embedding_text_ko = '{sql_escape(embedding_text)}' "
        f"WHERE {' OR '.join(where_clauses)};"
    )


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate SQL updates for wine.embedding_text_ko from source JSON.")
    parser.add_argument("input_json", help="Path to source wine JSON array")
    parser.add_argument("output_sql", help="Path to output SQL file")
    args = parser.parse_args()

    input_path = Path(args.input_json)
    output_path = Path(args.output_sql)

    with input_path.open("r", encoding="utf-8") as file:
        wines = json.load(file)

    statements = [
        "BEGIN;",
        "-- generated by generate_embedding_update_sql.py",
    ]

    for wine in wines:
        statement = build_update_statement(wine)
        if statement:
            statements.append(statement)

    statements.append("COMMIT;")
    output_path.write_text("\n".join(statements) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
