# 이후 validate로 수정
spring.jpa.hibernate.ddl-auto=update
management.metrics.tags.application=${spring.application.name}_prod

# Swagger Server URL for Prod
swagger.server-url=https://j14a505.p.ssafy.io
server.forward-headers-strategy=framework