spring.application.name=Jupasu
spring.profiles.active=dev

# Database Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Redis Configuration
spring.data.redis.host=${SPRING_DATA_REDIS_HOST}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT}

# Email Configuration (Google SMTP - SSL 465)
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# JWT Configuration
jwt.secret=${JWT_SECRET}
jwt.access.expiration=3600000
jwt.refresh.expiration=604800000

# CORS Configuration
auth.cors.allowed-origins=${ALLOWED_ORIGINS:http://localhost:3000}

# Prometheus Configuration
management.endpoints.web.exposure.include=prometheus
management.endpoints.prometheus.enabled=true
management.metrics.tags.application=${spring.application.name}