spring.jpa.hibernate.ddl-auto=update
management.metrics.tags.application=${spring.application.name}_dev

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.generate_statistics=true
logging.level.org.hibernate.stat=debug

# Swagger Server URL for Dev
swagger.server-url=https://j14a505.p.ssafy.io:8443
server.forward-headers-strategy=framework