from __future__ import annotations

import argparse
import json
import os
from datetime import datetime, timezone
from pathlib import Path

import httpx


ROOT = Path(__file__).resolve().parents[2]
DEFAULT_INPUT_JSON = ROOT / "data" / "vivino_ultra_results_kr_food_dedup.json"
DEFAULT_OUTPUT_SQL = ROOT / "back" / "src" / "main" / "resources" / "sql" / "recommendation" / "04_backfill_embedding_vectors.sql"
DEFAULT_MODEL = "text-embedding-3-small"
DEFAULT_BASE_URL = "https://gms.ssafy.io/gmsapi/api.openai.com/v1/embeddings"


def load_dotenv_file(path: Path) -> None:
    if not path.exists():
        return

    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            continue
        key, value = stripped.split("=", 1)
        os.environ.setdefault(key.strip(), value.strip().strip("'").strip('"'))


def sql_escape(value: str) -> str:
    return value.replace("'", "''")


def vector_literal(values: list[float]) -> str:
    return "[" + ",".join(f"{value:.12f}" for value in values) + "]"


def build_where_clause(wine: dict) -> str:
    clauses: list[str] = []

    name_en = (wine.get("wine_name") or "").strip()
    name_kr = (wine.get("name_kr") or "").strip()

    if name_en:
        clauses.append(f"name_en = '{sql_escape(name_en)}'")
    if name_kr:
        clauses.append(f"name_kr = '{sql_escape(name_kr)}'")

    return " OR ".join(clauses)


def fetch_embedding(client: httpx.Client, api_key: str, model: str, text: str) -> list[float]:
    response = client.post(
        DEFAULT_BASE_URL,
        headers={
            "Content-Type": "application/json",
            "Authorization": f"Bearer {api_key}",
        },
        json={
            "model": model,
            "input": text,
        },
        timeout=60.0,
    )
    response.raise_for_status()
    data = response.json()
    return data["data"][0]["embedding"]


def build_update_statement(wine: dict, model: str, generated_at: str, vector: str) -> str | None:
    where_clause = build_where_clause(wine)
    if not where_clause:
        return None

    return (
        "UPDATE wine "
        f"SET embedding = '{vector}'::vector, "
        f"embedding_model = '{sql_escape(model)}', "
        f"embedding_generated_at = '{generated_at}' "
        f"WHERE ({where_clause}) AND (embedding IS NULL);"
    )


def main() -> None:
    load_dotenv_file(ROOT / ".env")

    parser = argparse.ArgumentParser(
        description="Generate SQL to backfill wine.embedding from the final Vivino JSON data using GMS embeddings."
    )
    parser.add_argument(
        "input_json",
        nargs="?",
        default=str(DEFAULT_INPUT_JSON),
        help=f"Path to the final Vivino JSON array file (default: {DEFAULT_INPUT_JSON})",
    )
    parser.add_argument(
        "output_sql",
        nargs="?",
        default=str(DEFAULT_OUTPUT_SQL),
        help=f"Path to the output SQL file (default: {DEFAULT_OUTPUT_SQL})",
    )
    parser.add_argument("--model", default=DEFAULT_MODEL)
    parser.add_argument("--limit", type=int, default=0, help="0 means all wines in the input JSON")
    args = parser.parse_args()

    api_key = os.environ.get("GMS_API_KEY")
    if not api_key:
        raise SystemExit("GMS_API_KEY environment variable is required.")

    input_path = Path(args.input_json)
    output_path = Path(args.output_sql)

    with input_path.open("r", encoding="utf-8") as file:
        wines = json.load(file)

    if args.limit > 0:
        wines = wines[: args.limit]

    generated_at = datetime.now(timezone.utc).isoformat()
    statements = [
        "BEGIN;",
        "-- generated by back/scripts/generate_embedding_vector_update_sql.py",
    ]

    with httpx.Client() as client:
        for index, wine in enumerate(wines, start=1):
            text = (wine.get("rich_description") or "").strip()
            if not text:
                continue
            embedding = fetch_embedding(client, api_key, args.model, text)
            vector = vector_literal(embedding)
            statement = build_update_statement(wine, args.model, generated_at, vector)
            if statement:
                statements.append(statement)
                print(f"[{index}/{len(wines)}] prepared embedding SQL for {wine.get('wine_name')}")

    statements.append("COMMIT;")
    output_path.write_text("\n".join(statements) + "\n", encoding="utf-8")
    print(f"Saved SQL to {output_path}")


if __name__ == "__main__":
    main()
