from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
DEFAULT_INPUT_JSON = ROOT / "data" / "vivino_ultra_results_kr_food_dedup.json"
DEFAULT_OUTPUT_SQL = ROOT / "back" / "src" / "main" / "resources" / "sql" / "recommendation" / "02_backfill_rich_description.sql"


def sql_escape(value: str) -> str:
    return value.replace("'", "''")


def build_where_clause(wine: dict) -> str:
    clauses: list[str] = []

    name_en = (wine.get("wine_name") or "").strip()
    name_kr = (wine.get("name_kr") or "").strip()

    if name_en:
        clauses.append(f"name_en = '{sql_escape(name_en)}'")
    if name_kr:
        clauses.append(f"name_kr = '{sql_escape(name_kr)}'")

    return " OR ".join(clauses)


def build_update_statement(wine: dict) -> str | None:
    where_clause = build_where_clause(wine)
    if not where_clause:
        return None

    rich_description = (wine.get("rich_description") or "").strip()
    if not rich_description:
        return None

    return (
        "UPDATE wine "
        f"SET rich_description = '{sql_escape(rich_description)}' "
        f"WHERE ({where_clause}) AND (rich_description IS NULL OR rich_description = '');"
    )


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate SQL to backfill wine.rich_description from the final Vivino JSON data."
    )
    parser.add_argument(
        "input_json",
        nargs="?",
        default=str(DEFAULT_INPUT_JSON),
        help=f"Path to the final Vivino JSON array file (default: {DEFAULT_INPUT_JSON})",
    )
    parser.add_argument(
        "output_sql",
        nargs="?",
        default=str(DEFAULT_OUTPUT_SQL),
        help=f"Path to the output SQL file (default: {DEFAULT_OUTPUT_SQL})",
    )
    args = parser.parse_args()

    input_path = Path(args.input_json)
    output_path = Path(args.output_sql)

    with input_path.open("r", encoding="utf-8") as file:
        wines = json.load(file)

    statements = [
        "BEGIN;",
        "-- generated by back/scripts/generate_embedding_text_ko_update_sql.py",
    ]

    for wine in wines:
        statement = build_update_statement(wine)
        if statement:
            statements.append(statement)

    statements.append("COMMIT;")
    output_path.write_text("\n".join(statements) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
