from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[2]
MINI_PROJECT_SRC = ROOT / "wine-pgvector-mini" / "src"
DEFAULT_INPUT_JSON = Path("C:/Users/SSAFY/Downloads/vivino_ultra_results_kr_food.json")
DEFAULT_OUTPUT_SQL = ROOT / "back" / "src" / "main" / "resources" / "sql" / "recommendation" / "02_backfill_embedding_text_ko.sql"

if str(MINI_PROJECT_SRC) not in sys.path:
    sys.path.insert(0, str(MINI_PROJECT_SRC))

from wine_pgvector_mini.transformer import build_embedding_text_ko  # noqa: E402


def sql_escape(value: str) -> str:
    return value.replace("'", "''")


def build_where_clause(wine: dict) -> str:
    clauses: list[str] = []

    name_en = (wine.get("wine_name") or "").strip()
    name_kr = (wine.get("name_kr") or "").strip()

    if name_en:
        clauses.append(f"name_en = '{sql_escape(name_en)}'")
    if name_kr:
        clauses.append(f"name_kr = '{sql_escape(name_kr)}'")

    return " OR ".join(clauses)


def build_update_statement(wine: dict) -> str | None:
    where_clause = build_where_clause(wine)
    if not where_clause:
        return None

    embedding_text_ko = build_embedding_text_ko(wine)

    return (
        "UPDATE wine "
        f"SET embedding_text_ko = '{sql_escape(embedding_text_ko)}' "
        f"WHERE ({where_clause}) AND (embedding_text_ko IS NULL OR embedding_text_ko = '');"
    )


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate SQL to backfill wine.embedding_text_ko from the final Vivino JSON data."
    )
    parser.add_argument(
        "input_json",
        nargs="?",
        default=str(DEFAULT_INPUT_JSON),
        help=f"Path to the final Vivino JSON array file (default: {DEFAULT_INPUT_JSON})",
    )
    parser.add_argument(
        "output_sql",
        nargs="?",
        default=str(DEFAULT_OUTPUT_SQL),
        help=f"Path to the output SQL file (default: {DEFAULT_OUTPUT_SQL})",
    )
    args = parser.parse_args()

    input_path = Path(args.input_json)
    output_path = Path(args.output_sql)

    with input_path.open("r", encoding="utf-8") as file:
        wines = json.load(file)

    statements = [
        "BEGIN;",
        "-- generated by back/scripts/generate_embedding_text_ko_update_sql.py",
    ]

    for wine in wines:
        statement = build_update_statement(wine)
        if statement:
            statements.append(statement)

    statements.append("COMMIT;")
    output_path.write_text("\n".join(statements) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
