export type ErrorCode =
  // 공통 예외
  | 'INTERNAL_SERVER_ERROR'
  | 'INVALID_REQUEST'
  | 'FORBIDDEN_ACCESS'
  // 회원 관련 예외
  | 'USER_NOT_FOUND'
  | 'INVALID_PASSWORD'
  | 'ACCOUNT_LOCKED'
  | 'EXISTING_EMAIL'
  | 'EXISTING_NICKNAME'
  | 'INVALID_NICKNAME_FORMAT'
  | 'INVALID_PASSWORD_FORMAT'
  | 'INVALID_CURRENT_PASSWORD'
  | 'PASSWORD_CONFIRM_NOT_MATCHED'
  | 'INVALID_SEARCH_KEYWORD'
  // OTP / 이메일 인증 관련 예외
  | 'OTP_EXPIRED_OR_INVALID'
  | 'OTP_INVALID'
  | 'OTP_MAX_ATTEMPTS_EXCEEDED'
  | 'SIGNUP_SESSION_EXPIRED'
  | 'SIGNUP_EMAIL_SEND_TOO_SOON'
  | 'EMAIL_NOT_VERIFIED'
  | 'PASSWORD_RESET_NOT_FOUND'

  // 인증 관련 예외
  | 'INVALID_TOKEN'
  | 'EXPIRED_TOKEN'
  | 'REFRESH_TOKEN_EXPIRED';
